import type { Product } from "@/types/product";

/**
 * TEMPORARY sample data so the Shop grid has something to render.
 * Names are intentionally generic placeholders, not real athletes.
 * Replace with real Supabase-backed product data in a later phase.
 */
export const PLACEHOLDER_PRODUCTS: Product[] = [
  {
    id: "1",
    slug: "sample-signer-1",
    name: "Sample Signer 1 — Signed & Framed Jersey",
    description: "Placeholder product for layout purposes.",
    price: 2499,
    imageUrl: "",
    quantity: 1,
    category: "Framed Jersey",
    published: true,
    sport: "Basketball",
    signerName: "Sample Signer 1",
    condition: "Mint",
    authenticated: true,
  },
  {
    id: "2",
    slug: "sample-signer-2",
    name: "Sample Signer 2 — Signed & Framed Jersey",
    description: "Placeholder product for layout purposes.",
    price: 2899,
    imageUrl: "",
    quantity: 1,
    category: "Framed Jersey",
    published: true,
    sport: "Football",
    signerName: "Sample Signer 2",
    condition: "Near Mint",
    authenticated: true,
  },
  {
    id: "3",
    slug: "sample-signer-3",
    name: "Sample Signer 3 — Signed & Framed Jersey",
    description: "Placeholder product for layout purposes.",
    price: 3499,
    imageUrl: "",
    quantity: 1,
    category: "Framed Jersey",
    published: true,
    sport: "Baseball",
    signerName: "Sample Signer 3",
    condition: "Mint",
    authenticated: true,
  },
  {
    id: "4",
    slug: "sample-signer-4",
    name: "Sample Signer 4 — Signed & Framed Jersey",
    description: "Placeholder product for layout purposes.",
    price: 1899,
    imageUrl: "",
    quantity: 0,
    category: "Framed Jersey",
    published: true,
    sport: "Hockey",
    signerName: "Sample Signer 4",
    condition: "Excellent",
    authenticated: true,
  },
  {
    id: "5",
    slug: "sample-signer-5",
    name: "Sample Signer 5 — Signed & Framed Jersey",
    description: "Placeholder product for layout purposes.",
    price: 4299,
    imageUrl: "",
    quantity: 1,
    category: "Framed Jersey",
    published: true,
    sport: "Soccer",
    signerName: "Sample Signer 5",
    condition: "Mint",
    authenticated: true,
  },
  {
    id: "6",
    slug: "sample-signer-6",
    name: "Sample Signer 6 — Signed & Framed Jersey",
    description: "Placeholder product for layout purposes.",
    price: 2199,
    imageUrl: "",
    quantity: 1,
    category: "Framed Jersey",
    published: true,
    sport: "Basketball",
    signerName: "Sample Signer 6",
    condition: "Near Mint",
    authenticated: true,
  },
];
